drop table if exists contact_category;
drop table if exists contact;

create table contact (
    id bigint generated by default as identity,
    address varchar(255),
    email varchar(255),
    gender integer not null,
    isFrequent boolean,
    mobile varchar(15),
    name varchar(100) not null,
    position varchar(255),
    category_id bigint,
    primary key (id)
);

create table contact_category (
    id bigint generated by default as identity,
    name varchar(100) not null,
    primary key (id)
);

alter table contact 
    add constraint FK38B7242070C63022 
    foreign key (category_id) 
    references contact_category;


